apiVersion: v1
kind: Service
metadata:
  name: client-api
  labels:
    app: client-api
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: client-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-api
  labels:
    app: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
        - name: client-api
          image: easylancer/client-api:latest
          imagePullPolicy: Always
          env:
            - name: DATA_API_URL
              value: "http://data-api.default.svc.cluster.local"
            - name: FILE_API_URL
              value: "https://2d5res4ff2.execute-api.eu-central-1.amazonaws.com/dev"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub
