apiVersion: v1
kind: Service
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
  selector:
    app: data-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-api
  labels:
    app: data-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-api
  template:
    metadata:
      labels:
        app: data-api
    spec:
      containers:
        - name: data-api
          image: easylancer/data-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
      imagePullSecrets:
        - name: dockerhub
