# Created by:
# kubectl create secret generic data-api-config --dry-run --from-literal=db-uri="[PASSWORD]" -o yaml \
#  | kubeseal -o yaml > secrets/data-api.config.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-api-config
  namespace: default
spec:
  encryptedData:
    db-uri: AgBDJ1+1YH5glSr8YDxmmHSGkRwHYiu7ihGw9/OJgm4pMBn4FsTTcw9EIGu/Z13cxhqjg2HWgqDl7plYGwvpUF46Qxc4VGEzoQCGZCJomU406vsLJuzbAwkoh6sV0EjaE6lDAhcHgLyzLULBbZ0acEADnbIcTH7fVxgVwQv2/iRP6TMKRPrWhU33tJW/LnN+appmCt8b8Z+8Asr5bQdw+sFTKcDkgsiLz4ch5UBl+Q50UeNLfbEeoI6YFTh8oYDs5gFlgHyKZRIO97RzEp0wb6gYUHmTReVBoojEuO/K1khtB9hWQw7+dDTZNAm6MjGLbJOhIo+k7HiHAPDywtrp60fSS9NcEFgOeaVmufRGPtd91Tn/FU4KGXDKOcfi9z4ZyzBq7aQ24yMCgJdNsZAjetja0oWp5aMpvCdwz+IMQVAuIahqpJIHR9/I1Q5SVlJlVfYvWkDj+CrT+Ile2FZSDuRDgNaSIjAz1oTkYbro8l12qQe//8N73CIp4fmO21gSb2yGAyC1dpdN6ovWdzc2zA+fqCZNy7V8YJi8+JYewo2+VHJWMgJuhhGESvh9NGupLWP1fSkrXFMr6S0sppR3Er3SjHlirBb9ESAmlTtOP00YkBM57CIVOorDZ/08hksVA8y+myXKL1Ne+JcewK+345NXVfF+fLKEzjrf2geg7PHVqq80TsDhIUugSzWs98bXgg3jz0594wR4MT5e+Rr/JFKfRMK14n2f8OtGIoD3kn+S1Q9xblyfdiixHvFVgxWh5qgeprfR55W/zmCEXr6bnfSBMpgl9sSFE+kT7r6haiq5UbBX/be3H0nZrg/0MyslAcSQWu97cPSvdXPSjgEmQTohKBa2OA25onFJKsi+AYaRpXaLiaDHxw/q+iHzZXXSPyQdZSC8MTfAeYZON0kH55a6MvZTnCtUjFi2CUy+70sztiB9SWkBxr1YSHEwfKju8hTg8mHaabj4qE/5O1mNpnJztByIUua/vckdrhHvCSGecx+g07N8azLSKEI4ZZpD4gBhLsem5Y9I+qygYm2jgWlKDNWiB4GmwsBRkMTfyQk1iQ==
  template:
    metadata:
      creationTimestamp: null
      name: data-api-config
      namespace: default
status: {}

