# Created by:
# kubectl create secret docker-registry dockerhub \
#    --dry-run --docker-server=https://index.docker.io/v1/ \
#    --docker-username=easylancer --docker-password=[PASSWORD] \
#    --docker-email=ahmed.saab.dev@gmail.com -o yaml \
# | kubeseal -o yaml > secrets/dockerhub.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCC+ivXV/LE3nzoDR/J60a6XNfEVzlbTG120tW+TW9wGADLmZtrrQL1M5rw7A5i1ZeZWjCKtkjcaZK5R5cB/9froIUS3/sqSUTVffZTwXIap3ysEtzGokOT7LR/e3achsX8Dg19OfgZkIRm6KgCljgsCc6Kl36keS0EMy6PgcW79f/pauQtNLIk0QzwQfwg1ZGefiqIjPEoBBJUg1Et3SJuAKD+lJyaxVOtmNKJ27SgwQPy1xDSt2XlviGA00crhBvOiZYGBh9ds+ebToyK5clErKrUpzTr4n4VY2Riqa7Xb3V3j6uNkvL1VyCvUraN0fDOHei9GBbf2s0oTCDaOC+Y0uXaOsxhowhPTouB+gfUUjCB/+oHDiXosy63L5OQAIq/k6xCWI/Xr2MfZyp3ppL3fF8R6nZEnV48/CbwcESeWgK7q7Z8yYwp6SQIC2AN49gbLzh2yYJH2Ki9XhysD8Gkq+xagmqoWf4I6k8wXvJKvCFAVOevf6G2zbl4iST/ly7ao43+f6hddNv6YH4TDEsg6PUDn0xJ/jI/risowkR7h3vaBTsk9mDHzYAzMp0hKJVgH6A7vp62s5eOdqsq/V6rSwJCQuJX/enqa/0n2XerPc0Fa/Gos9cZnNwfv0vigDABtCb9voExiC8y8y+JcivsHvRmUZPY+fhRmhgxSZgdL/zxCCe2CqhZJwpJtHy6cCJzxJhb1dpabIP/iQXwMAxfelt/GvKApg2Yb6S+mxQs6NW80uhDHc3lNQNHsZvzidT6oM8mUUW+eoZLEBLEncBzv+J9L54pPTw9Qh/ExEoJs5c34Ubw0rWbfjqPiuqa35XgpmINqEMIJLVu+lY8kB064EgqXkTIXHe0M+NuN580Og17NHumpWUucNsOd8oz3EnHxzTwLzAcUZtFuX/k8s86/VTn
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: default
    type: kubernetes.io/dockerconfigjson
status: {}

